import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim, setCacheNameDetails } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// CRITICAL: Skip waiting immediately to activate new service worker
self.skipWaiting();
clientsClaim();

// Integrate OneSignal v16 SDK
try {
  self.importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');
} catch (e) {
  console.error('[SW] OneSignal importScripts failed:', e);
}

// Get app version from Vite define
const APP_VERSION = self.__APP_VERSION__ || '0.0.0';
console.log(`[SW] Service Worker v${APP_VERSION} initializing...`);

// Configuration to enforce versioning in cache names
setCacheNameDetails({
  prefix: 'artist-booking',
  suffix: `v${APP_VERSION}`,
  precache: 'precache',
  runtime: 'runtime'
});

// Cleanup caches from older versions - this is critical for updates
cleanupOutdatedCaches();

// Also manually clean up old caches on activation
self.addEventListener('activate', (event) => {
  console.log(`[SW] Activating Service Worker v${APP_VERSION}`);
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((cacheName) => {
            // Delete any cache that doesn't match current version
            return !cacheName.includes(`v${APP_VERSION}`);
          })
          .map((cacheName) => {
            console.log(`[SW] Deleting old cache: ${cacheName}`);
            return caches.delete(cacheName);
          })
      );
    }).then(() => {
      console.log(`[SW] Service Worker v${APP_VERSION} now active and controlling all clients`);
      // Take control of all clients immediately
      return self.clients.claim();
    })
  );
});

// Log when service worker is installed
self.addEventListener('install', (event) => {
  console.log(`[SW] Installing Service Worker v${APP_VERSION}`);
  // Force the waiting service worker to become the active service worker
  self.skipWaiting();
});

// Precache build artifacts (assets, js, css generated by Vite)
precacheAndRoute(self.__WB_MANIFEST);

// -- Runtime Caching Strategies --

// 1. Google Fonts (Cache First)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: `google-fonts-v${APP_VERSION}`,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 Year
      }),
    ],
  })
);

// 2. Artist Uploaded Files (StaleWhileRevalidate) -> Instant load from cache, refresh in background
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/files/'),
  new StaleWhileRevalidate({
    cacheName: `voucher-images-v${APP_VERSION}`,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// 3. General Images (Cache First)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: `images-v${APP_VERSION}`,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// 3. API Requests (Network First) - always try network first
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: `api-v${APP_VERSION}`,
    networkTimeoutSeconds: 10,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes freshness
      }),
    ],
  })
);

// 4. Navigation requests (Network First) - ensures fresh HTML
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: `pages-v${APP_VERSION}`,
    networkTimeoutSeconds: 5,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// -- Message Handler for Manual Updates --
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    console.log('[SW] Received SKIP_WAITING message, activating immediately');
    self.skipWaiting();
  }

  if (event.data && event.data.type === 'GET_VERSION') {
    event.ports[0].postMessage({ version: APP_VERSION });
  }

  if (event.data && event.data.type === 'CLEAR_CACHES') {
    console.log('[SW] Clearing all caches...');
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            console.log(`[SW] Deleting cache: ${cacheName}`);
            return caches.delete(cacheName);
          })
        );
      }).then(() => {
        console.log('[SW] All caches cleared');
        if (event.ports[0]) {
          event.ports[0].postMessage({ success: true });
        }
      })
    );
  }
});

// -- Push Notification Handlers --

// -- Push Notification Handlers --
self.addEventListener('push', (event) => {
  console.log('[SW] Push received', event);

  if (!event.data) {
    console.log('[SW] Push error: No data');
    return;
  }

  try {
    const data = event.data.json();
    console.log('[SW] Push data:', JSON.stringify(data, null, 2));

    // If this is a OneSignal notification, it has a 'custom' property
    // The OneSignal SDK (which we imported above) will handle this automatically.
    // We skip our custom handler to avoid duplicate notifications.
    if (data && (data.custom || data.userId || data.app_id)) {
      console.log('[SW] OneSignal payload detected, letting SDK handle it');
      return;
    }

    const title = data.title || 'New Notification';
    const options = {
      body: data.body || 'You have a new notification',
      icon: data.icon || '/icon-192.png',
      badge: data.badge || '/icon-192.png',
      data: { url: data.data?.url || data.url || '/' },
      requireInteraction: true,
      actions: [
        { action: 'open', title: 'Open' }
      ]
    };

    console.log('[SW] Showing notification:', title, options);

    event.waitUntil(
      self.registration.showNotification(title, options)
        .catch(err => console.error('[SW] Show notification failed:', err))
    );
  } catch (err) {
    console.error('[SW] Push processing failed or non-JSON payload:', err);
  }
});

self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked', event);

  // If this is a OneSignal notification, let the SDK handle it
  if (event.notification.data && (event.notification.data.custom || event.notification.data.userId)) {
    console.log('[SW] OneSignal click detected, letting SDK handle it');
    return;
  }

  event.notification.close();

  const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href;

  const promiseChain = clients.matchAll({
    type: 'window',
    includeUncontrolled: true
  }).then((windowClients) => {
    // Check if there is already a window/tab open with the target URL
    for (let i = 0; i < windowClients.length; i++) {
      const client = windowClients[i];
      // Check if client url matches (ignoring query params if needed, or exact match)
      // Using includes or startsWith might be safer for SPA routes
      if (client.url === urlToOpen || client.url.startsWith(urlToOpen)) {
        return client.focus();
      }
    }
    // If not, open a new window
    if (clients.openWindow) {
      return clients.openWindow(urlToOpen);
    }
  });

  event.waitUntil(promiseChain);
});
