import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {response} from './ivory-fixtures.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.AUDIT_BROWSER});
const base=process.env.AUDIT_URL||'http://127.0.0.1:5210';
const out=process.env.AUDIT_OUTPUT||'output/tattoi-details-sheets';await mkdir(out,{recursive:true});
const results=[];
try{for(const width of [320,390,820]){
 const context=await browser.newContext({viewport:{width,height:900},hasTouch:true,serviceWorkers:'block'});
 await context.addInitScript(()=>{localStorage.setItem('authToken','test');localStorage.setItem('ui_debug_enabled','false');localStorage.setItem('tattoi-theme-override','light');sessionStorage.setItem('splashShown','true');});
 const errors=[],calls=[];
 await context.route('**/*',async route=>{
  const url=new URL(route.request().url());if(url.hostname!=='127.0.0.1')return route.abort();
  if(!url.pathname.startsWith('/api/trpc/'))return route.continue();
  const names=url.pathname.split('/').at(-1).split(',');return route.fulfill({json:names.map(name=>{
   calls.push(name);let value=response(name,'client');
   if(name==='sessionPlans.getByClient')value=[{...value[0],projectName:'Botanical forearm',id:22}];
   if(name==='sessionPlans.getById')value={...value,projectName:'Botanical forearm',id:22,items:value.items.map(i=>({...i,estimateCents:60000}))};
   return {result:{data:{json:value}}};
  })});
 });
 const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/bookings');
 const proposal=page.getByRole('button',{name:/Botanical forearm.*View booking proposal/});await proposal.waitFor();
 assert.equal(await page.getByRole('dialog').count(),0);
 assert.equal(await page.getByText('Platform fee',{exact:true}).count(),0);
 await page.screenshot({path:`${out}/bookings-${width}.png`,fullPage:true});
 await proposal.click();
 let sheet=page.getByRole('dialog',{name:'Review your booking',exact:true});await sheet.waitFor();
 await sheet.getByText('Platform fee',{exact:true}).waitFor();await sheet.getByText('$5.10',{exact:true}).waitFor();
 assert(await sheet.evaluate(el=>el.dataset.side==='bottom'&&!el.closest('main')));
 await sheet.getByRole('button',{name:/Sitting 1/}).click();
 let detail=page.getByRole('dialog',{name:'Sitting 1',exact:true});await detail.waitFor();await detail.getByText('180 minutes',{exact:true}).waitFor();
 assert.equal(await detail.getByRole('button',{name:'Close',exact:true}).count(),1);
 await detail.getByRole('button',{name:'Close',exact:true}).click();await sheet.waitFor();
 await page.screenshot({path:`${out}/proposal-${width}.png`});
 await sheet.getByRole('button',{name:'Close',exact:true}).click();await proposal.waitFor();
 assert(!calls.includes('sessionPlans.acceptAndPay'));
 await page.getByRole('button',{name:'View sittings',exact:true}).first().click();
 sheet=page.getByRole('dialog',{name:'Project sittings',exact:true});await sheet.waitFor();
 await sheet.getByRole('button',{name:/Sitting /}).first().click();
 detail=page.getByRole('dialog',{name:/Sitting \d+ ·/});await detail.waitFor();await detail.getByText('Balance due',{exact:true}).waitFor();
 await detail.getByRole('button',{name:'Close',exact:true}).click();await sheet.waitFor();
 await sheet.getByRole('button',{name:'Close',exact:true}).click();
 await page.goto(base+'/projects/12?session=101&view=Payments');
 sheet=page.getByRole('dialog',{name:'Payments',exact:true});await sheet.waitFor();
 await sheet.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('dialog',{name:'Project sittings',exact:true}).waitFor();
 await page.goto(base+'/projects/12?session=101');
 detail=page.getByRole('dialog',{name:/Sitting \d+ ·/});await detail.waitFor();
 await detail.getByRole('button',{name:'Request a date change',exact:true}).click();
 await page.getByRole('textbox',{name:'Message',exact:true}).waitFor();
 assert(!calls.includes('messages.send'));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);results.push({width,status:'passed',checks:['compact proposal','review and platform fee','portalled bottom sheets','nested sitting details','one close per sheet','return to parent','project sitting details','payment deep link','message draft without sending','no overflow or runtime errors']});
 await context.close();
}}finally{await browser.close();await writeFile(`${out}/results.json`,JSON.stringify(results,null,2));}
console.log(JSON.stringify(results,null,2));
