import {readFile,writeFile} from 'node:fs/promises';
const root='output/main-refresh';
const before=JSON.parse(await readFile(root+'/before/results.json','utf8'));
const after=JSON.parse(await readFile(root+'/after/results.json','utf8'));
const dark=JSON.parse(await readFile(root+'/after-dark/results.json','utf8'));
const summary={baselineCommit:'aca9ee8df96102f5b05fa2f0bdfa520576a50919',lightCases:after.length,darkCases:dark.length,controlChanges:[],overflowRegressions:[],textDifferences:[],geometryChanges:[]};
for(const current of after){
 const base=before.find(x=>x.id===current.id);if(!base)continue;
 if(JSON.stringify(current.controls)!==JSON.stringify(base.controls))summary.controlChanges.push(current.id);
 if(current.overflow&&!base.overflow)summary.overflowRegressions.push(current.id);
 if(current.text!==base.text)summary.textDifferences.push(current.id);
 const boxes=current.boxes.filter((v,i)=>base.boxes[i]?.tag===v.tag&&(Math.abs(v.h-base.boxes[i].h)>2||Math.abs(v.y-base.boxes[i].y)>10));
 if(boxes.length)summary.geometryChanges.push({id:current.id,count:boxes.length});
}
await writeFile(root+'/comparison.json',JSON.stringify(summary,null,2));
const screens=[...new Map(after.map(x=>[x.role+x.path,{role:x.role,path:x.path}])).values()];
await writeFile(root+'/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tattoi · Main refresh</title><style>
*{box-sizing:border-box}body{margin:0;background:#f8f6f2;color:#29231e;font:16px/1.5 -apple-system,BlinkMacSystemFont,sans-serif}header,main{max-width:1280px;margin:auto;padding:28px}h1{font:400 48px/1.1 Georgia,serif;letter-spacing:-2px;margin:12px 0}p{max-width:850px;color:#746c64}code{background:#eee8df;padding:3px 7px;border-radius:5px}.controls{display:flex;gap:16px;flex-wrap:wrap;margin-top:24px}label{display:grid;gap:5px;font-size:13px}select{padding:12px;border:1px solid #e5e0d9;background:#fffdfa;color:#29231e;border-radius:10px;font:inherit}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:28px}figure{margin:0;min-width:0}figcaption{font-weight:600;padding:12px 0}img{display:block;max-width:100%;height:auto;max-height:1000px;object-fit:contain;object-position:top left;border:1px solid #e5e0d9;border-radius:18px;background:white}.note{padding:18px;background:#eee8df;border-radius:12px;margin-top:24px;font-size:14px}a{color:inherit}@media(max-width:650px){header,main{padding:18px}.comparison{gap:12px}h1{font-size:36px}}
</style><header><small>TATTOI / ORIGINAL APP / IVORY THEME</small><h1>Main, refreshed.</h1><p>The original <code>main</code> screens and workflows, styled with the Ivory palette and typography on <code>main-refresh</code>. These are screenshots of the implemented app using isolated test data.</p><div class="controls"><label>Screen<select id="screen"></select></label><label>Viewport<select id="width"><option>320</option><option selected>390</option><option>820</option><option>1440</option></select></label><label>Refresh theme<select id="theme"><option value="light">Ivory light</option><option value="dark">Ivory dark</option></select></label></div><div class="note">44 light comparisons · 22 dark captures · 11 theme checks passed. Original merchant placeholders, 8 existing test failures and 146 existing TypeScript diagnostics remain. Live Stripe and physical iPhone keyboard/momentum behaviour were not certified.</div></header><main><div class="comparison"><figure><figcaption>Original main · light</figcaption><img id="before" alt="Original main screenshot"></figure><figure><figcaption id="afterLabel">Main refresh · Ivory</figcaption><img id="after" alt="Refreshed Ivory screenshot"></figure></div><p>Dark screenshots are available at 390 and 820 pixels. Login content animates in the original app, so the displayed text may differ by capture timing.</p></main><script>
const screens=${JSON.stringify(screens)};const screen=document.querySelector('#screen'),width=document.querySelector('#width'),theme=document.querySelector('#theme');screens.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=s.role+' · '+s.path;screen.append(o)});function update(){if(theme.value==='dark'&&!['390','820'].includes(width.value))width.value='390';const s=screens[screen.value],id=s.role+'-'+s.path.replaceAll('/','-')+'-'+width.value;document.querySelector('#before').src='before/'+id+'.png';document.querySelector('#after').src=(theme.value==='dark'?'after-dark/':'after/')+id+'.png';document.querySelector('#afterLabel').textContent='Main refresh · Ivory '+theme.value;}[screen,width,theme].forEach(el=>el.addEventListener('change',update));update();</script></html>`);
console.log(summary);
