/** Public route inventory for real artist practice smoke checks. Pages are defined only in ArtistRoutes. */
export const PRACTICE_SCREENS = [
  ["Today", "/dashboard"],
  ["Calendar", "/calendar"],
  ["Inbox", "/conversations"],
  ["Business", "/business"],
  ["Money", "/money"],
  ["Payout history", "/payout-history"],
  ["Supplies", "/supplies"],
  ["Supply orders", "/supply-orders"],
  ["Purchases", "/purchases"],
  ["Shopfront", "/shopfront"],
  ["Products", "/products"],
  ["Events", "/artist-events"],
  ["Store orders", "/store-orders"],
  ["Studio", "/studio"],
  ["Studio invitations", "/studio?view=invitations"],
  ["Waitlist", "/waitlist"],
  ["Profile & portfolio", "/artist-profile"],
  ["Settings", "/settings"],
  ["Notifications", "/notifications-management"],
  ["Subscription", "/subscriptions"],
  ["Booking request", "/lead/1"],
  ...[
    "profile",
    "business",
    "booking-link",
    "regulation",
    "travel",
    "data-import",
    "instagram",
    "consultations",
    "danger-zone",
  ].map(s => [s.replaceAll("-", " "), `/settings?section=${s}`]),
] as const;
